version: "3"

services:

  oidc-provider:
    build: provider/
    ports:
      - "8081:8080"

  rucio-db:
    image: postgres:11
    environment:
      - POSTGRES_USER=rucio
      - POSTGRES_DB=rucio
      - POSTGRES_PASSWORD=secret
    command: ["-c", "fsync=off","-c", "synchronous_commit=off","-c", "full_page_writes=off"]

  rucio-db-init:
    image: rucio/rucio-init:release-${RUCIO_VERSION_DB_INIT}
    depends_on:
      - rucio-db
    environment:
      - RUCIO_CFG_DATABASE_DEFAULT=postgresql://rucio:secret@rucio-db/rucio
      - RUCIO_CFG_BOOTSTRAP_USERPASS_IDENTITY=rse
      - RUCIO_CFG_BOOTSTRAP_USERPASS_PWD=secret

  rucio:
    image: rucio/rucio-server:release-${RUCIO_VERSION_SERVER}
    ports:
      - "8443:443"
    depends_on:
      - rucio-db
      - oidc-provider
    environment:
      - RDBMS=postgres11
      - RUCIO_ENABLE_SSL=True
      - RUCIO_LOG_LEVEL=debug
      - RUCIO_SERVER_TYPE=all
      - RUCIO_CFG_DATABASE_DEFAULT=postgresql://rucio:secret@rucio-db/rucio
      - RUCIO_CFG_MONITOR_CARBON_SERVER=graphite
      - RUCIO_CFG_MONITOR_CARBON_PORT=8125
      - RUCIO_CFG_MONITOR_USER_SCOPE=docker
      - RUCIO_CFG_WEBUI_AUTH_TYPE=userpass
      - RUCIO_CFG_API_ENDPOINTS=accountlimits, accounts, archives, auth, config, credentials, dids, dirac, export, heartbeats, identities, import, lifetime_exceptions, locks, meta, ping, redirect, replicas, requests, rses, rules, scopes, subscriptions, tmp_dids, traces, vos

  rucio-ui:
    image: rucio/rucio-ui:release-${RUCIO_VERSION_UI}
    ports:
      - "443:443"
    depends_on:
      - rucio
    environment:
      - RUCIO_LOG_LEVEL=debug
      - RUCIO_CFG_DATABASE_DEFAULT=postgresql://rucio:secret@rucio-db/rucio
      - RUCIO_CFG_MONITOR_CARBON_SERVER=graphite
      - RUCIO_CFG_MONITOR_CARBON_PORT=8125
      - RUCIO_CFG_MONITOR_USER_SCOPE=docker
      - RUCIO_PROXY=https://rucio-dev.ornl.gov:8443
      - RUCIO_AUTH_PROXY=https://rucio-dev.ornl.gov:8443

  graphite:
    image: graphiteapp/graphite-statsd:latest
    ports:
      - "8080:80"

  fts:
    image: rucio/fts:latest
    ports:
      - "8446:8446"
      - "8449:8449"

  ftsdb:
    image: mysql:5
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=fts
      - MYSQL_PASSWORD=fts
      - MYSQL_ROOT_PASSWORD=fts
      - MYSQL_DATABASE=fts

  xrd1:
    image: rucio/xrootd-noauth:latest
    ports:
      - "1094:1094"
    environment:
      - XRDPORT=1094

  xrd2:
    image: rucio/xrootd-noauth:latest
    ports:
      - "1095:1095"
    environment:
      - XRDPORT=1095

  xrd3:
    image: rucio/xrootd-noauth:latest
    ports:
      - "1096:1096"
    environment:
      - XRDPORT=1096

  xrd4:
    image: rucio/xrootd-noauth:latest
    ports:
      - "1097:1097"
    environment:
      - XRDPORT=1097

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password
    command: ["server", "/data"]

